CREATE DATABASE RAW_DB;
use raw_db;
CREATE SCHEMA RAW_SCHEMA;
USE SCHEMA RAW_SCHEMA;


CREATE OR REPLACE TABLE RAW_BORROWERS (
  BORROWER_ID      STRING,
  FIRST_NAME       STRING,
  LAST_NAME        STRING,
  EMAIL            STRING,
  PHONE            STRING,
  SEGMENT          STRING,
  CITY             STRING,
  STATE            STRING,
  COUNTRY          STRING,
  DOB              STRING,
  EMPLOYMENT_TYPE  STRING,
  UPDATED_AT       STRING,
  -- metadata
  LOAD_TS          TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  SOURCE_FILE_NAME STRING
);

-- BRANCHES
CREATE OR REPLACE TABLE RAW_BRANCHES (
  BRANCH_ID        STRING,
  BRANCH_NAME      STRING,
  REGION           STRING,
  CITY             STRING,
  STATE            STRING,
  COUNTRY          STRING,
  OPEN_DATE        STRING,
  STATUS           STRING,
  -- metadata
  LOAD_TS          TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  SOURCE_FILE_NAME STRING
);

select * from raw_branches;
-- LOAN TRANSACTIONS
CREATE OR REPLACE TABLE RAW_LOAN_TXN (
  TXN_ID             STRING,
  TXN_LINE_ID        STRING,
  TXN_DATE           STRING,
  LOAN_ID            STRING,
  BORROWER_ID        STRING,
  BRANCH_ID          STRING,
  TXN_TYPE           STRING,
  AMOUNT             STRING,
  INTEREST_COMPONENT STRING,
  FEE_COMPONENT      STRING,
  PAYMENT_MODE       STRING,
  TXN_STATUS         STRING,
  -- metadata
  LOAD_TS            TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  SOURCE_FILE_NAME   STRING
);

-- LOANS
CREATE OR REPLACE TABLE RAW_LOANS (
  LOAN_ID            STRING,
  BORROWER_ID        STRING,
  BRANCH_ID          STRING,
  LOAN_TYPE          STRING,
  PRINCIPAL_AMOUNT   STRING,
  INTEREST_RATE      STRING,
  TENURE_MONTHS      STRING,
  DISBURSE_DATE      STRING,
  LOAN_STATUS        STRING,
  SECURITY_TYPE      STRING,
  UPDATED_AT         STRING,
  -- metadata
  LOAD_TS            TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  SOURCE_FILE_NAME   STRING
);

CREATE OR REPLACE FILE FORMAT RAW_DB.RAW_SCHEMA.FF_CSV
TYPE = CSV
FIELD_DELIMITER = ','
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
SKIP_HEADER = 1
TRIM_SPACE = TRUE
NULL_IF = ('', 'NULL', 'null')
ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;

CREATE OR REPLACE STORAGE INTEGRATION LOAN_S3_INT
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = S3
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::498504718091:role/myrolealok2'
STORAGE_ALLOWED_LOCATIONS = ('s3://mybucketalok2/Project_LMA/landing/loan_mgmt/');

describe integration loan_s3_int;

CREATE OR REPLACE STAGE raw_db.raw_schema.STG_LOAN_S3
URL = 's3://mybucketalok2/Project_LMA/landing/loan_mgmt/'
STORAGE_INTEGRATION = LOAN_S3_INT
FILE_FORMAT = FF_CSV;

list @stg_loan_s3;

CREATE OR REPLACE PIPE RAW_DB.RAW_SCHEMA.PIPE_RAW_BORROWERS
AUTO_INGEST = TRUE
AS
COPY INTO RAW_DB.RAW_SCHEMA.RAW_BORROWERS
(
  BORROWER_ID,
  FIRST_NAME,
  LAST_NAME,
  EMAIL,
  PHONE,
  SEGMENT,
  CITY,
  STATE,
  COUNTRY,
  DOB,
  EMPLOYMENT_TYPE,
  UPDATED_AT,
  LOAD_TS,
  SOURCE_FILE_NAME
)
FROM (
  SELECT
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    TO_TIMESTAMP_NTZ($12),
    CURRENT_TIMESTAMP(),
    METADATA$FILENAME
  FROM @RAW_DB.RAW_SCHEMA.STG_LOAN_S3/borrowers
)
ON_ERROR = CONTINUE;

CREATE OR REPLACE PIPE RAW_DB.RAW_SCHEMA.PIPE_RAW_BRANCHES
AUTO_INGEST = TRUE
AS
COPY INTO RAW_DB.RAW_SCHEMA.RAW_BRANCHES
(
  BRANCH_ID,
  BRANCH_NAME,
  REGION,
  CITY,
  STATE,
  COUNTRY,
  OPEN_DATE,
  STATUS,
  LOAD_TS,
  SOURCE_FILE_NAME
)
FROM (
  SELECT
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    CURRENT_TIMESTAMP(),
    METADATA$FILENAME
  FROM @RAW_DB.RAW_SCHEMA.STG_LOAN_S3/branches
)
ON_ERROR = CONTINUE;

CREATE OR REPLACE PIPE RAW_DB.RAW_SCHEMA.PIPE_RAW_LOANS
AUTO_INGEST = TRUE
AS
COPY INTO RAW_DB.RAW_SCHEMA.RAW_LOANS
(
  LOAN_ID,
  BORROWER_ID,
  BRANCH_ID,
  LOAN_TYPE,
  PRINCIPAL_AMOUNT,
  INTEREST_RATE,
  TENURE_MONTHS,
  DISBURSE_DATE,
  LOAN_STATUS,
  SECURITY_TYPE,
  UPDATED_AT,
  LOAD_TS,
  SOURCE_FILE_NAME
)
FROM (
  SELECT
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    TO_TIMESTAMP_NTZ($11),
    CURRENT_TIMESTAMP(),
    METADATA$FILENAME
  FROM @RAW_DB.RAW_SCHEMA.STG_LOAN_S3/loans
)
ON_ERROR = CONTINUE;

CREATE OR REPLACE PIPE RAW_DB.RAW_SCHEMA.PIPE_RAW_LOAN_TXN
AUTO_INGEST = TRUE
AS
COPY INTO RAW_DB.RAW_SCHEMA.RAW_LOAN_TXN
(
  TXN_ID,
  TXN_LINE_ID,
  TXN_DATE,
  LOAN_ID,
  BORROWER_ID,
  BRANCH_ID,
  TXN_TYPE,
  AMOUNT,
  INTEREST_COMPONENT,
  FEE_COMPONENT,
  PAYMENT_MODE,
  TXN_STATUS,
  LOAD_TS,
  SOURCE_FILE_NAME
)
FROM (
  SELECT
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    CURRENT_TIMESTAMP(),
    METADATA$FILENAME
  FROM @RAW_DB.RAW_SCHEMA.STG_LOAN_S3/transactions
)
ON_ERROR = CONTINUE;

show pipes;

SELECT * FROM RAW_BORROWERS;

SELECT * FROM RAW_BRANCHES;

SELECT * FROM RAW_LOANS;

SELECT * FROM RAW_LOAN_TXN;


ALTER PIPE PIPE_RAW_BORROWERS REFRESH;
ALTER PIPE PIPE_RAW_BRANCHES REFRESH;
ALTER PIPE PIPE_RAW_LOANS REFRESH;
ALTER PIPE PIPE_RAW_LOAN_TXN REFRESH;

select * from raw_borrowers;